version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /tissue-micro-array-analysis.ga
  testParameterFiles:
  - /tissue-micro-array-analysis-tests.yml
  authors:
  - name: Cameron Watson
    orcid: 0000-0002-6942-2469
